### ISSUE TITLE
关于视频和封面文件格式的问题

### ISSUE THREAD

**Issue by 454270186** [bytedance-youthcamp-jbzx/tiktok#1]
您好，我在实现publish/list这个接口的时候遇到了问题，我返回的playURL和coverURL在前端都不能正常的显示出来，视频也显示不支持播放该格式的视频，我想问一下前端支持的是什么文件格式的封面和视频

**Comment by magbone** [comment]
首先检查一下返回的playURL和coverURL在浏览器中能够打开，我们的封面和视频存储在MinIO中，在获取的时候根据object name（在上传的时候生成object name并存在数据库中）获取url再返回给前端。封面和视频在测试的时候分别选用jpg和mp4的格式。
