### ISSUE TITLE
关于Apifox文档的问题

### ISSUE THREAD

**Issue by Vinci-217** [bytedance-youthcamp-jbzx/tiktok#4]
您好！想要学习一下本项目，发现Apifox文档过期了，请问能否再帮忙延长时间学习一下呢？
非常感谢！

**Comment by 0202zc** [comment]
> 您好！想要学习一下本项目，发现Apifox文档过期了，请问能否再帮忙延长时间学习一下呢？ 非常感谢！

已延长

**Comment by Vinci-217** [comment]
> > 您好！想要学习一下本项目，发现Apifox文档过期了，请问能否再帮忙延长时间学习一下呢？ 非常感谢！
> 
> 已延长

https://www.apifox.cn/apidoc/shared-09d88f32-0b6c-4157-9d07-a36d32d7a75c
是这个链接吗，还是打不开

![image](https://github.com/user-attachments/assets/dc1b0da7-7d77-4d9d-8bbf-dd0c91dcc266)

**Comment by 0202zc** [comment]
> > > 您好！想要学习一下本项目，发现Apifox文档过期了，请问能否再帮忙延长时间学习一下呢？ 非常感谢！
> > 
> > 
> > 已延长
> 
> https://www.apifox.cn/apidoc/shared-09d88f32-0b6c-4157-9d07-a36d32d7a75c 是这个链接吗，还是打不开
> 
> ![image](https://private-user-images.githubusercontent.com/115935217/395862075-dc1b0da7-7d77-4d9d-8bbf-dd0c91dcc266.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyNzM1MzUsIm5iZiI6MTczNDI3MzIzNSwicGF0aCI6Ii8xMTU5MzUyMTcvMzk1ODYyMDc1LWRjMWIwZGE3LTdkNzctNGQ5ZC04YmJmLWRkMGM5MWRjYzI2Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNVQxNDMzNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNjJjMWMyZDM1MjgxMmUyY2NlYzZlZDc0ZjlkMzYwOGM0NDA2ZGVmOGJlM2FjNTFhMjM2NjAzZDBiMzc0YmZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.7t_iMOMsTpAPY5qoM7x7t4cYawyq7pMf9yAEOtTm34s)

感谢指正！重新生成了一下，应该可以打开了：https://apifox.com/apidoc/shared-7b33652d-6080-41bb-a70e-7a165d55daae

**Comment by Vinci-217** [comment]
> > > > 您好！想要学习一下本项目，发现Apifox文档过期了，请问能否再帮忙延长时间学习一下呢？ 非常感谢！
> > > 
> > > 
> > > 已延长
> > 
> > 
> > https://www.apifox.cn/apidoc/shared-09d88f32-0b6c-4157-9d07-a36d32d7a75c 是这个链接吗，还是打不开
> > ![image](https://private-user-images.githubusercontent.com/115935217/395862075-dc1b0da7-7d77-4d9d-8bbf-dd0c91dcc266.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyNzM1MzUsIm5iZiI6MTczNDI3MzIzNSwicGF0aCI6Ii8xMTU5MzUyMTcvMzk1ODYyMDc1LWRjMWIwZGE3LTdkNzctNGQ5ZC04YmJmLWRkMGM5MWRjYzI2Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNVQxNDMzNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNjJjMWMyZDM1MjgxMmUyY2NlYzZlZDc0ZjlkMzYwOGM0NDA2ZGVmOGJlM2FjNTFhMjM2NjAzZDBiMzc0YmZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.7t_iMOMsTpAPY5qoM7x7t4cYawyq7pMf9yAEOtTm34s)
> 
> 感谢指正！重新生成了一下，应该可以打开了：https://apifox.com/apidoc/shared-7b33652d-6080-41bb-a70e-7a165d55daae

非常感谢(*^▽^*)！
